version: 2.1
orbs:
  katalon-studio: katalon/katalon-studio@23.0.9
workflows:
  build:
    jobs:
      - katalon-studio/run:
          machine: true
          resource_class: demo-self-hosted/slowey
          version: latest
          command_arguments: >-
            -browserType='Chrome' -retry=0 -statusDelay=15 -testSuitePath='Test
            Suites/TS_RegressionTest'
